const MetaDataKeywords: string[] = [
    "Next.js",
    "Portfolio",

    "Terris",
    "Terris Tan",
    "Terris Tan Wei Jun",
    "Tan Wei Jun Terris",

    "Terris Portfolio",
    "Terris Tan Portfolio",
    "Terris Tan Wei Jun Portfolio",
    "Tan Wei Jun Terris Portfolio",

    "Frontend",
    "Backend",
    "API",
    "Cloud",

    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "RESTful API",
    "Cloud Solutions",
    "AWS",
    "Google Cloud",
    "Azure",
    "DevOps",

    "SWE",
    "Software Engineer",
    "Solutions Engineer",
    "Solution Architecture",
    "UI/UX Design",
    "UI/UX Developer",

    "AI",
    "Machine Learning",
    "Artificial Intelligence",
    "ML Engineer",
    "Data Science",
    "Algorithms",

    "Singapore",
    "SMU",
    "Singapore Management University",
    "Information Systems",
    "Penultimate Student",

    "Hackathon",
    "Coding Competitions",
    "Tech Projects",
    "Web Development",
    "App Development",

    "Internships",
    "Tech Internships",
    "Student Developer",
    "Full Stack Applications",
    "Software Projects",
    "Technology Enthusiast",

    // Add more keywords here
    "Blockchain",
    "Cybersecurity",
    "Data Encryption",
    "Homomorphic Encryption",
    "Data Privacy",
    "Smart Contracts",
    "Decentralized Applications",
    "DApps",
    "Web3",
    "Cryptography",
    "Digital Transformation",
    "AI in Web Development",
    "Responsive Design",
    "Single Page Applications",
    "SPA",
    "Progressive Web Apps",
    "PWA",
    "JavaScript",
    "TypeScript",
    "React",
    "React.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "NoSQL",
    "GraphQL",
    "REST API",
    "API Development",
    "Microservices",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Continuous Integration",
    "Continuous Deployment",
    "Agile Development",
    "Scrum",
    "Kanban",
    "Git",
    "GitHub",
    "Version Control",
    "JIRA",
    "Software Development Lifecycle",
    "SDLC",
    "Test-Driven Development",
    "TDD",
    "Behavior-Driven Development",
    "BDD",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "E2E Testing",
    "User Experience",
    "User Interface",
    "Design Systems",
    "Component Libraries",
    "Material UI",
    "Tailwind CSS",
    "Bootstrap",
    "Chakra UI",
    "Figma",
    "Adobe XD",
    "InVision",
    "Wireframing",
    "Prototyping",
    "Design Thinking",
    "Human-Centered Design",
    "HCI",
    "Human-Computer Interaction",
    "API Security",
    "OAuth",
    "JWT",
    "Token Authentication",
    "Serverless Architecture",
    "AWS Lambda",
    "Azure Functions",
    "Cloud Computing",
    "Infrastructure as Code",
    "IaC",
    "Terraform",
    "Ansible",
    "Networking",
    "Load Balancing",
    "Scalability",
    "Performance Optimization",
    "Responsive Web Design",
    "Cross-Browser Compatibility",
    "Mobile-First Design",
    "Accessibility",
    "WCAG",
    "SEO Optimization",
    "Meta Tags",
    "Page Speed",
    "Content Management",
    "Content Delivery Network",
    "CDN",
    "Analytics",
    "Google Analytics",
    "Data Visualization",

    // Another 100 keywords
    "Python",
    "Django",
    "Flask",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "ASP.NET",
    "C#",
    "Java",
    "Spring Boot",
    "Go",
    "Golang",
    "Rust",
    "Swift",
    "Kotlin",
    "Android Development",
    "iOS Development",
    "Mobile Development",
    "React Native",
    "Flutter",
    "Xamarin",
    "Unity",
    "Game Development",
    "AR/VR",
    "Augmented Reality",
    "Virtual Reality",
    "3D Modeling",
    "Blender",
    "Unity3D",
    "Unreal Engine",
    "DevOps Engineer",
    "Cloud Engineer",
    "System Design",
    "Design Patterns",
    "Software Architecture",
    "Enterprise Applications",
    "Big Data",
    "Hadoop",
    "Spark",
    "Kafka",
    "Data Engineering",
    "ETL",
    "Data Warehousing",
    "Snowflake",
    "Redshift",
    "Business Intelligence",
    "BI Tools",
    "Tableau",
    "Power BI",
    "Looker",
    "Data Analytics",
    "Data Mining",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "Deep Learning",
    "Neural Networks",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-Learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Jupyter Notebook",
    "Data Science Projects",
    "MLOps",
    "Model Deployment",
    "AutoML",
    "Feature Engineering",
    "Data Preprocessing",
    "Cross-Validation",
    "Hyperparameter Tuning",
    "Gradient Descent",
    "Convolutional Neural Networks",
    "CNN",
    "Recurrent Neural Networks",
    "RNN",
    "Transformers",
    "Attention Mechanism",
    "Generative AI",
    "Chatbots",
    "AI Ethics",
    "Bias in AI",
    "Explainable AI",
    "XAI",
    "Reinforcement Learning",
    "RL",
    "Autonomous Systems",
    "Edge Computing",
    "IoT",
    "Internet of Things",
    "Smart Devices",
    "Smart Homes",
    "Wearables",
    "HealthTech",
    "FinTech",
    "InsurTech",
    "PropTech",
    "AgriTech",
    "EdTech",
    "LegalTech",

    // Another 100 keywords
    "Responsive Web Apps",
    "Static Site Generators",
    "Gatsby",
    "Next.js Projects",
    "JAMstack",
    "Headless CMS",
    "Contentful",
    "Strapi",
    "Sanity",
    "Ghost",
    "Netlify",
    "Vercel",
    "Server-Side Rendering",
    "SSR",
    "Client-Side Rendering",
    "CSR",
    "Hydration",
    "WebAssembly",
    "Wasm",
    "Performance Tuning",
    "Lazy Loading",
    "Code Splitting",
    "Tree Shaking",
    "Babel",
    "Webpack",
    "Parcel",
    "Rollup",
    "Browser Compatibility",
    "Polyfills",
    "BEM Methodology",
    "CSS Modules",
    "Styled Components",
    "SASS",
    "SCSS",
    "LESS",
    "PostCSS",
    "Responsive Images",
    "WebP",
    "SVG",
    "Vector Graphics",
    "Canvas API",
    "WebGL",
    "Three.js",
    "D3.js",
    "Data Visualization Tools",
    "Chart.js",
    "Vega",
    "Plotly",
    "Highcharts",
    "Apache ECharts",
    "Infographics",
    "UI Animation",
    "Framer Motion",
    "Greensock",
    "GSAP",
    "ScrollMagic",
    "AOS",
    "Intersection Observer",
    "Observer Pattern",
    "Event-Driven Architecture",
    "Micro Frontends",
    "Monorepo",
    "Nx",
    "Lerna",
    "Yarn Workspaces",
    "NPM",
    "Node Package Manager",
    "Continuous Deployment",
    "GitOps",
    "ArgoCD",
    "Helm",
    "Service Mesh",
    "Istio",
    "Envoy",
    "API Gateway",
    "Kong",
    "Nginx",
    "Load Testing",
    "Stress Testing",
    "Chaos Engineering",
    "Gremlin",
    "Security Testing",
    "Penetration Testing",
    "OWASP",
    "Cross-Site Scripting",
    "XSS",
    "SQL Injection",
    "SAST",
    "DAST",
    "Fuzz Testing",
    "Vulnerability Scanning",
    "Zero Trust Architecture",
    "Identity and Access Management",
    "IAM",
    "Single Sign-On",
    "SSO",
    "Multi-Factor Authentication",
    "MFA",
    "Biometric Authentication",
    "Passwordless Authentication",
];

export default MetaDataKeywords;
